name: QueueCTL Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 25.x
      uses: actions/setup-node@v4
      with:
        node-version: 25.x
        
    - name: Install dependencies
      run: npm install
      
    - name: Run Readable Tests
      run: node .queuectl-tests/custom/readable_tests.js
